2024-03-27 21:26:13,961 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-03-27 21:26:13,961 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Configure stats pid to 29076
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Antoine\.config\wandb\settings
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Antoine\Desktop\CentraleSupelec\6_Reinforcement learning\Project\RL-Humanoid\wandb\settings
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-27 21:26:13,962 WARNING MainThread:29076 [wandb_setup.py:_flush():76] Could not find program at -m src.ppo
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m src.ppo'}
2024-03-27 21:26:13,962 INFO    MainThread:29076 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:_log_setup():527] Logging user logs to C:\Users\Antoine\Desktop\CentraleSupelec\6_Reinforcement learning\Project\RL-Humanoid\wandb\run-20240327_212613-7ca2foo9\logs\debug.log
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:_log_setup():528] Logging internal logs to C:\Users\Antoine\Desktop\CentraleSupelec\6_Reinforcement learning\Project\RL-Humanoid\wandb\run-20240327_212613-7ca2foo9\logs\debug-internal.log
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:init():567] calling init triggers
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:init():617] starting backend
2024-03-27 21:26:13,963 INFO    MainThread:29076 [wandb_init.py:init():621] setting up manager
2024-03-27 21:26:13,965 INFO    MainThread:29076 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-27 21:26:13,966 INFO    MainThread:29076 [wandb_init.py:init():629] backend started and connected
2024-03-27 21:26:13,971 INFO    MainThread:29076 [wandb_init.py:init():721] updated telemetry
2024-03-27 21:26:14,026 INFO    MainThread:29076 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-03-27 21:26:14,921 INFO    MainThread:29076 [wandb_run.py:_on_init():2344] communicating current version
2024-03-27 21:26:15,614 INFO    MainThread:29076 [wandb_run.py:_on_init():2353] got version response 
2024-03-27 21:26:15,614 INFO    MainThread:29076 [wandb_init.py:init():805] starting run threads in backend
2024-03-27 21:26:16,627 WARNING MainThread:29076 [wandb_init.py:init():1209] interrupted
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\site-packages\wandb\sdk\wandb_init.py", line 1187, in init
    run = wi.init()
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\site-packages\wandb\sdk\wandb_init.py", line 818, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\threading.py", line 600, in wait
    signaled = self._cond.wait(timeout)
  File "C:\ProgramData\anaconda3\envs\MujocoProject\lib\threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-03-27 21:26:26,173 WARNING MsgRouterThr:29076 [router.py:message_loop():77] message_loop has been closed
